return {
    WINDOW_WIDTH = 800,
    WINDOW_HEIGHT = 600,

    SEPARATOR_STROKE_LENGTH = 20,
    SEPARATOR_STROKE_COUNT = 60,

    BALL_RADIUS = 20,
    BALL_SPEED = 1000,

    PADDLE_WIDTH = 20,
    PADDLE_HEIGHT = 150,
    PADDLE_SPEED = 1600,

    SCORE_TO_WIN = 11
}
